FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    php-fpm \
    php-mysql \
    wget \
    php-cli

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY conf/www.conf /etc/php/7.4/fpm/pool.d/

COPY tools/setup.sh /tmp/setup.sh

RUN chmod +x /tmp/setup.sh
RUN /tmp/setup.sh

WORKDIR /var/www/wordpress

EXPOSE 9000

CMD ["php-fpm7.4", "-F"]